FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./
COPY api/package.json ./api/
COPY web/package.json ./web/
COPY shared/package.json ./shared/

RUN yarn install --frozen-lockfile

COPY shared/ ./shared/
COPY web/ ./web/

RUN yarn workspace shared build && \
    yarn workspace web build

FROM caddy:2-alpine

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /app/web/dist /srv

EXPOSE 80 443
